#!/bin/sh /etc/rc.common
# Copyright (C) 2014-2014 Xs
START=90
STOP=90

start() {
        /usr/bin/adbyby/adbyby &
        iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8118
}